#pragma once

enum LHObjectEnum {
    o_fake_transition = 0,
    o_opt_multichoice = 1,
    o_tile_selfdestruct = 2,
    o_cancel_upload_button_new_ui = 3,
    o_vis_eff_perk = 4,
    o_exit_game_button = 5,
    o_opt_fight_speed_button_new_ui = 6,
    o_opt_tmsleep_button = 7,
    o_space_field = 8,
    o_opt_gamepad_button_new_ui = 9,
    o_sound_settings_new_ui = 10,
    __TWITCH_obj_twitchManager = 11,
    o_opt_cursor = 12,
    o_opt_menu_razdelbutton = 13,
    o_effects_volume_slider = 14,
    o_menu_savemenu_delwindow = 15,
    o_scroller = 16,
    o_piramidka = 17,
    o_opt_fspeed_allow_button = 18,
    o_crea_dia_faces = 19,
    o_opt_font_button = 20,
    o_vis_eff_item = 21,
    o_opt_herocolor_choices_new_ui = 22,
    o_camp_resource_main = 23,
    o_opt_herocolor_choices = 24,
    o_copy_save_slot_button_new_ui = 25,
    o_cancel_download_button_new_ui = 26,
    o_start_game_button = 27,
    o_speeds_slider = 28,
    o_vis_eff_campbut = 29,
    o_achievement_button = 30,
    o_continue_button = 31,
    o_eff_witch = 32,
    o_vis_eff_enemy = 33,
    o_game_settings_new_ui = 34,
    o_base_slider_new_ui = 35,
    o_tweener = 36,
    o_opt_roadoutline = 37,
    o_tile_lightdestruct = 38,
    o_opt_crt_button_new_ui = 39,
    o_opt_pause_focus_button_new_ui = 40,
    o_disable_steam_cloud_button_new_ui = 41,
    o_menu_message = 42,
    o_opt_button = 43,
    o_game_saved = 44,
    o_opt_herocolor = 45,
    o_tutorial_skip_button = 46,
    o_tile_verticality = 47,
    o_camp_alchemy_anim = 48,
    o_opt_pause_battle_item_hover_button_new_ui = 49,
    o_roadsurf = 50,
    o_opt_lang_button_new_ui = 51,
    o_cancel_button_new_ui = 52,
    o_warning_save_dialog_new_ui = 53,
    o_error_message_switch_steam_cloud = 54,
    o_camp_encyclo_category_button = 55,
    o_settings_menu_new_ui = 56,
    o_opt_heroarrow = 57,
    o_menu_fullscreens_button = 58,
    o_sachiv_button = 59,
    o_opt_lang_button = 60,
    o_opt_speedrun_button_new_ui = 61,
    o_opt_pause_battle_button_new_ui = 62,
    o_menu_fontaccess_button = 63,
    o_master_volume_slider = 64,
    o_language_menu = 65,
    o_opt_speedrun_button = 66,
    o_crea_dia_controller = 67,
    oCloudSaves = 68,
    o_opt_item_pause_button = 69,
    o_speeds_button = 70,
    o_download_button_new_ui = 71,
    o_opt_pause_battle_unit_hover_button_new_ui = 72,
    o_music_volume_slider = 73,
    o_opt_mnstr_pause_button = 74,
    o_slider = 75,
    o_menu_savemenu_new_ui = 76,
    o_vis_eff_heroload = 77,
    o_opt_herocolor_new_ui = 78,
    o_opt_pause_loop_button_new_ui = 79,
    o_language_button = 80,
    o_customization_settings_new_ui = 81,
    o_opt_cursor_new_ui = 82,
    o_eff_storm = 83,
    o_opt_full_button = 84,
    o_opt_font_button_new_ui = 85,
    o_joy_cursor = 86,
    o_dust_particle = 87,
    o_opt_focuspause_button = 88,
    o_delete_save_slot_button_new_ui = 89,
    o_switch_controller = 90,
    o_menu_savemenu_new_ui_switch_steam = 91,
    o_enable_steam_cloud_button_new_ui = 92,
    o_upload_button_new_ui = 93,
    o_opt_gamepad_button = 94,
    o_save_slot_new_ui_switch_steam = 95,
    objSignIn = 96,
    o_start_save_slot_button_new_ui = 97,
    o_video_settings_new_ui = 98,
    o_deck_switch_button = 99,
    o_camp_equip_switch_button = 100,
    o_room_transition = 101,
    o_save_game_button_new_ui = 102,
    o_opt_crt_button = 103,
    o_loading = 104,
    o_menu = 105,
    o_controller = 106,
    o_camp_controller = 107,
    o_intro_controller = 108,
    o_save_slot_new_ui = 109,
    o_dialog = 110,
    o_menu_savemenu = 111,
    o_button = 112,
    o_menu_savemenu_button = 113,
    o_menu_button = 114,
    o_menu_full_button = 115,
    o_menu_lang_button = 116,
    o_menu_langflag_button = 117,
    o_menu_VK = 118,
    o_menu_TW = 119,
    o_rezimy = 120,
    o_speed = 121,
    o_resitm_switch = 122,
    o_perks_button = 123,
    o_retreat = 124,
    o_menuopen_button = 125,
    o_camp_resource = 126,
    o_stats_button = 127,
    o_itemgetpanel = 128,
    o_rezimy_mob = 129,
    o_rezimimob_button = 130,
    o_camp_expmenu = 131,
    o_camp_expstart_button = 132,
    o_camp_expsquare_button = 133,
    o_deck_button = 134,
    o_menu_savemenu_delbutton = 135,
    o_deck_card = 136,
    o_camp_shopmenu = 137,
    o_camp_shop_button = 138,
    o_camp_begunok = 139,
    o_camp_statistik = 140,
    o_camp_begunok_stat = 141,
    o_camp_equipmenu = 142,
    o_camp_equipmenu_sort = 143,
    o_camp_begunok_equip = 144,
    o_camp_equipstat_slider = 145,
    o_camp_equipstat_button = 146,
    o_camp_equip_buttons = 147,
    o_camp_equip_slots = 148,
    o_camp_equip_items = 149,
    o_camp_equip_up = 150,
    o_camp_equip_down = 151,
    o_camp_craftmenu = 152,
    o_camp_craftmenu_button = 153,
    o_camp_craft_items = 154,
    o_camp_craft_up = 155,
    o_camp_craft_down = 156,
    o_camp_craft_anim = 157,
    o_camp_upgrademenu = 158,
    o_camp_upgrademenu_button = 159,
    o_camp_demolishmenu = 160,
    o_camp_demolishmenu_button = 161,
    o_camp_encyclo = 162,
    o_camp_button = 163,
    o_camp_encyclo_razdelbutton = 164,
    o_camp_encyclo_buttons = 165,
    o_camp_encyclo_enemysprite = 166,
    o_camp_begunok_encyclo_l = 167,
    o_camp_begunok_encyclo_r = 168,
    o_camp_encyclo_dialog = 169,
    o_camp_encyclo_razdelopen = 170,
    o_camp_alchemymenu = 171,
    o_camp_alchemymenu_button = 172,
    o_camp_alchemy_buttons = 173,
    o_camp_alchemy_up = 174,
    o_camp_alchemy_down = 175,
    o_camp_tile = 176,
    o_camp_tile_light = 177,
    o_camp_game_button = 178,
    o_camp_build_button = 179,
    o_camp_stat_button = 180,
    o_camp_craft_button = 181,
    o_camp_equip_button = 182,
    o_camp_encyclo_button = 183,
    o_camp_alchemy_button = 184,
    o_vis_eff_hero_whole = 185,
    o_camp_destroy_button = 186,
    o_camp_upgrade_button = 187,
    o_camp_showupgrade_button = 188,
    o_random_road = 189,
    o_road_gen = 190,
    o_random_road_lim = 191,
    o_road_gen_lim = 192,
    o_opt_battle_pause_button = 193,
    o_tutorial_road = 194,
    o_tutorial_road_gen = 195,
    o_dead_menu = 196,
    o_dead_button = 197,
    o_dead_getall_button = 198,
    o_resource_sliced = 199,
    o_continue = 200,
    o_confirm_button_new_ui = 201,
    o_fight_window = 202,
    o_fight_hero = 203,
    o_fight_enemy = 204,
    o_fight_range_enemy = 205,
    o_fight_ally = 206,
    o_fight_range_ally = 207,
    o_fight_buffs = 208,
    o_textflow = 209,
    o_lightning = 210,
    o_arrows = 211,
    o_roots = 212,
    o_bloodtrees = 213,
    o_pautinka = 214,
    o_ghostchain = 215,
    o_stainedglass = 216,
    o_vis_eff_omega = 217,
    o_fight_window_buffs = 218,
    o_card = 219,
    o_enemy = 220,
    o_road = 221,
    o_card_place = 222,
    o_tile_forget = 223,
    o_tile_remember = 224,
    o_effects = 225,
    o_opt_loop_pause_button = 226,
    o_eff_light = 227,
    o_vis_eff_hero = 228,
    o_eff_timelight_plus = 229,
    o_eff_vamp = 230,
    o_eff_ghost = 231,
    o_eff_firefly = 232,
    o_eff_bloodtrees = 233,
    o_eff_lonebloodtrees = 234,
    o_eff_lightning = 235,
    o_eff_swamp = 236,
    o_eff_lib = 237,
    o_eff_smithy = 238,
    o_eff_pause_lvl = 239,
    o_eff_lib_destr = 240,
    o_eff_doubleday = 241,
    o_eff_zastawa = 242,
    o_item = 243,
    o_equip_slot = 244,
    o_invslot = 245,
    o_heal_effect = 246,
    o_camp_encyclo_resource_monsters = 247,
    o_exp_effect = 248,
    o_cardplace_effect = 249,
    o_ramka = 250,
    o_settings_button_new_ui = 251,
    o_potion = 252,
    o_resource = 253,
    o_resource_get = 254,
    o_furniture = 255,
    o_furniture_get = 256,
    o_roga_trophy = 257,
    o_roga_trophy_get = 258,
    o_perks_window = 259,
    o_perks_begunok = 260,
    o_perks_window_button = 261,
    o_not_road = 262,
    o_hero = 263,
    o_hero_skeleton = 264,
    o_enemy_fly = 265,
    o_nadpis_small = 266,
    o_nadpis_big = 267,
    o_visual_effect = 268,
    o_expeff = 269,
    o_enemy_newquest = 270,
    o_road_show = 271,
    o_leach_appear = 272,
    o_cutscene_1 = 273,
    o_music_maker = 274,
    o_vis_eff_card = 275,
    o_musicmaker_note = 276,
    o_musicmaker_button = 277,
    o_musicmaker_bararrow = 278,
    o_cursor = 279,
    o_pause = 280,
    o_tutor_text = 281,
    o_win_help = 282,
    ubg_transition_obj = 283,
    o_bossappear_effect = 284,
    o_empty = 285,
    o_effect_itembroke = 286,
    o_effect_enemybroke = 287,
    o_meowgila = 288,
    o_blackhole = 289,
    o_highlight_road_slider = 290,
    o_highlight_hero_slider = 291,
    o_camp_perk_menu_button = 292,
    o_base_button = 293,
    o_camp_perk_menu = 294,
    o_menu_close_button = 295,
    o_camp_perk = 296,
    o_text_button = 297,
    o_camp_deck_menu = 298,
    o_menu_savemenu_retreat_button = 299,
    __YYInternalObject__300 = 300,
};

namespace LHObjects {

    const char* GetObjectName(int id) {
        static const char* names[] = {
            "o_fake_transition",
            "o_opt_multichoice",
            "o_tile_selfdestruct",
            "o_cancel_upload_button_new_ui",
            "o_vis_eff_perk",
            "o_exit_game_button",
            "o_opt_fight_speed_button_new_ui",
            "o_opt_tmsleep_button",
            "o_space_field",
            "o_opt_gamepad_button_new_ui",
            "o_sound_settings_new_ui",
            "__TWITCH_obj_twitchManager",
            "o_opt_cursor",
            "o_opt_menu_razdelbutton",
            "o_effects_volume_slider",
            "o_menu_savemenu_delwindow",
            "o_scroller",
            "o_piramidka",
            "o_opt_fspeed_allow_button",
            "o_crea_dia_faces",
            "o_opt_font_button",
            "o_vis_eff_item",
            "o_opt_herocolor_choices_new_ui",
            "o_camp_resource_main",
            "o_opt_herocolor_choices",
            "o_copy_save_slot_button_new_ui",
            "o_cancel_download_button_new_ui",
            "o_start_game_button",
            "o_speeds_slider",
            "o_vis_eff_campbut",
            "o_achievement_button",
            "o_continue_button",
            "o_eff_witch",
            "o_vis_eff_enemy",
            "o_game_settings_new_ui",
            "o_base_slider_new_ui",
            "o_tweener",
            "o_opt_roadoutline",
            "o_tile_lightdestruct",
            "o_opt_crt_button_new_ui",
            "o_opt_pause_focus_button_new_ui",
            "o_disable_steam_cloud_button_new_ui",
            "o_menu_message",
            "o_opt_button",
            "o_game_saved",
            "o_opt_herocolor",
            "o_tutorial_skip_button",
            "o_tile_verticality",
            "o_camp_alchemy_anim",
            "o_opt_pause_battle_item_hover_button_new_ui",
            "o_roadsurf",
            "o_opt_lang_button_new_ui",
            "o_cancel_button_new_ui",
            "o_warning_save_dialog_new_ui",
            "o_error_message_switch_steam_cloud",
            "o_camp_encyclo_category_button",
            "o_settings_menu_new_ui",
            "o_opt_heroarrow",
            "o_menu_fullscreens_button",
            "o_sachiv_button",
            "o_opt_lang_button",
            "o_opt_speedrun_button_new_ui",
            "o_opt_pause_battle_button_new_ui",
            "o_menu_fontaccess_button",
            "o_master_volume_slider",
            "o_language_menu",
            "o_opt_speedrun_button",
            "o_crea_dia_controller",
            "oCloudSaves",
            "o_opt_item_pause_button",
            "o_speeds_button",
            "o_download_button_new_ui",
            "o_opt_pause_battle_unit_hover_button_new_ui",
            "o_music_volume_slider",
            "o_opt_mnstr_pause_button",
            "o_slider",
            "o_menu_savemenu_new_ui",
            "o_vis_eff_heroload",
            "o_opt_herocolor_new_ui",
            "o_opt_pause_loop_button_new_ui",
            "o_language_button",
            "o_customization_settings_new_ui",
            "o_opt_cursor_new_ui",
            "o_eff_storm",
            "o_opt_full_button",
            "o_opt_font_button_new_ui",
            "o_joy_cursor",
            "o_dust_particle",
            "o_opt_focuspause_button",
            "o_delete_save_slot_button_new_ui",
            "o_switch_controller",
            "o_menu_savemenu_new_ui_switch_steam",
            "o_enable_steam_cloud_button_new_ui",
            "o_upload_button_new_ui",
            "o_opt_gamepad_button",
            "o_save_slot_new_ui_switch_steam",
            "objSignIn",
            "o_start_save_slot_button_new_ui",
            "o_video_settings_new_ui",
            "o_deck_switch_button",
            "o_camp_equip_switch_button",
            "o_room_transition",
            "o_save_game_button_new_ui",
            "o_opt_crt_button",
            "o_loading",
            "o_menu",
            "o_controller",
            "o_camp_controller",
            "o_intro_controller",
            "o_save_slot_new_ui",
            "o_dialog",
            "o_menu_savemenu",
            "o_button",
            "o_menu_savemenu_button",
            "o_menu_button",
            "o_menu_full_button",
            "o_menu_lang_button",
            "o_menu_langflag_button",
            "o_menu_VK",
            "o_menu_TW",
            "o_rezimy",
            "o_speed",
            "o_resitm_switch",
            "o_perks_button",
            "o_retreat",
            "o_menuopen_button",
            "o_camp_resource",
            "o_stats_button",
            "o_itemgetpanel",
            "o_rezimy_mob",
            "o_rezimimob_button",
            "o_camp_expmenu",
            "o_camp_expstart_button",
            "o_camp_expsquare_button",
            "o_deck_button",
            "o_menu_savemenu_delbutton",
            "o_deck_card",
            "o_camp_shopmenu",
            "o_camp_shop_button",
            "o_camp_begunok",
            "o_camp_statistik",
            "o_camp_begunok_stat",
            "o_camp_equipmenu",
            "o_camp_equipmenu_sort",
            "o_camp_begunok_equip",
            "o_camp_equipstat_slider",
            "o_camp_equipstat_button",
            "o_camp_equip_buttons",
            "o_camp_equip_slots",
            "o_camp_equip_items",
            "o_camp_equip_up",
            "o_camp_equip_down",
            "o_camp_craftmenu",
            "o_camp_craftmenu_button",
            "o_camp_craft_items",
            "o_camp_craft_up",
            "o_camp_craft_down",
            "o_camp_craft_anim",
            "o_camp_upgrademenu",
            "o_camp_upgrademenu_button",
            "o_camp_demolishmenu",
            "o_camp_demolishmenu_button",
            "o_camp_encyclo",
            "o_camp_button",
            "o_camp_encyclo_razdelbutton",
            "o_camp_encyclo_buttons",
            "o_camp_encyclo_enemysprite",
            "o_camp_begunok_encyclo_l",
            "o_camp_begunok_encyclo_r",
            "o_camp_encyclo_dialog",
            "o_camp_encyclo_razdelopen",
            "o_camp_alchemymenu",
            "o_camp_alchemymenu_button",
            "o_camp_alchemy_buttons",
            "o_camp_alchemy_up",
            "o_camp_alchemy_down",
            "o_camp_tile",
            "o_camp_tile_light",
            "o_camp_game_button",
            "o_camp_build_button",
            "o_camp_stat_button",
            "o_camp_craft_button",
            "o_camp_equip_button",
            "o_camp_encyclo_button",
            "o_camp_alchemy_button",
            "o_vis_eff_hero_whole",
            "o_camp_destroy_button",
            "o_camp_upgrade_button",
            "o_camp_showupgrade_button",
            "o_random_road",
            "o_road_gen",
            "o_random_road_lim",
            "o_road_gen_lim",
            "o_opt_battle_pause_button",
            "o_tutorial_road",
            "o_tutorial_road_gen",
            "o_dead_menu",
            "o_dead_button",
            "o_dead_getall_button",
            "o_resource_sliced",
            "o_continue",
            "o_confirm_button_new_ui",
            "o_fight_window",
            "o_fight_hero",
            "o_fight_enemy",
            "o_fight_range_enemy",
            "o_fight_ally",
            "o_fight_range_ally",
            "o_fight_buffs",
            "o_textflow",
            "o_lightning",
            "o_arrows",
            "o_roots",
            "o_bloodtrees",
            "o_pautinka",
            "o_ghostchain",
            "o_stainedglass",
            "o_vis_eff_omega",
            "o_fight_window_buffs",
            "o_card",
            "o_enemy",
            "o_road",
            "o_card_place",
            "o_tile_forget",
            "o_tile_remember",
            "o_effects",
            "o_opt_loop_pause_button",
            "o_eff_light",
            "o_vis_eff_hero",
            "o_eff_timelight_plus",
            "o_eff_vamp",
            "o_eff_ghost",
            "o_eff_firefly",
            "o_eff_bloodtrees",
            "o_eff_lonebloodtrees",
            "o_eff_lightning",
            "o_eff_swamp",
            "o_eff_lib",
            "o_eff_smithy",
            "o_eff_pause_lvl",
            "o_eff_lib_destr",
            "o_eff_doubleday",
            "o_eff_zastawa",
            "o_item",
            "o_equip_slot",
            "o_invslot",
            "o_heal_effect",
            "o_camp_encyclo_resource_monsters",
            "o_exp_effect",
            "o_cardplace_effect",
            "o_ramka",
            "o_settings_button_new_ui",
            "o_potion",
            "o_resource",
            "o_resource_get",
            "o_furniture",
            "o_furniture_get",
            "o_roga_trophy",
            "o_roga_trophy_get",
            "o_perks_window",
            "o_perks_begunok",
            "o_perks_window_button",
            "o_not_road",
            "o_hero",
            "o_hero_skeleton",
            "o_enemy_fly",
            "o_nadpis_small",
            "o_nadpis_big",
            "o_visual_effect",
            "o_expeff",
            "o_enemy_newquest",
            "o_road_show",
            "o_leach_appear",
            "o_cutscene_1",
            "o_music_maker",
            "o_vis_eff_card",
            "o_musicmaker_note",
            "o_musicmaker_button",
            "o_musicmaker_bararrow",
            "o_cursor",
            "o_pause",
            "o_tutor_text",
            "o_win_help",
            "ubg_transition_obj",
            "o_bossappear_effect",
            "o_empty",
            "o_effect_itembroke",
            "o_effect_enemybroke",
            "o_meowgila",
            "o_blackhole",
            "o_highlight_road_slider",
            "o_highlight_hero_slider",
            "o_camp_perk_menu_button",
            "o_base_button",
            "o_camp_perk_menu",
            "o_menu_close_button",
            "o_camp_perk",
            "o_text_button",
            "o_camp_deck_menu",
            "o_menu_savemenu_retreat_button",
            "__YYInternalObject__300"
        };

        if (id < 0 || id > 300) return "Unknown";
        return names[id];
    }
}